#!/usr/bin/python

# @desc     Grab the changed files using 'svn st' then run sniffer on those.
# @install  Put in directory in $PATH. chmod+x the file.
# @author   Mike Pearce <mike@mikepearce.net>
# @since    18/05/2010

# Grab some libraries
import os
import sys
import commands


#-------------------
def show_error(error="Undefined Error!", exitcode = 1):
#-------------------
    """Writes an error to stderr"""
    sys.stderr.write(error +"\n")
    sys.exit(exitcode)

#-------------------
# Now, onto the main event!
#-------------------
if __name__ == "__main__":

    # First, make sure we've got a .svn dir
    if os.path.exists('.svn'):

        # First, run svn st
        out = commands.getoutput('svn st');

        # Check we have changed files
        if ( len(out) == 0 ):
            show_error('There are no changed files', 0)

        # For each change, run phpcs
        for line in out.split('\n'):

            # Make sure teh change ISN'T root
            if (line[8:] != '.'):

                # Inform
                #sys.stdout.write('Sniffing "'+ line[8:] +'"\n')

                # Run the command
                cmd = '/usr/local/php5/bin/phpcs '+ line[8:]
                out = commands.getoutput(cmd);

                # If codesniffr isn't installed
                if ( out.find('No such file or directory') != -1 ):
                    show_error('You do not have PHPCS installed!\n'+out)
                else:
                    sys.stdout.write(out)

    # Maybe it's git?
    #else:
    else:
	show_error('This is not an svn repo.')

